### ISSUE TITLE
Initializer with showProgressGuide boolean does not work

### ISSUE THREAD

**Issue by Ahaubster** [kentya6/KYCircularProgress#10]
I had to set the showProgressGuide after initialization for it to work, even when I set this value to true in the parameters for the initializer.

**Comment by kentya6** [comment]
Hi, @Ahaubster.

I fixed this issue in https://github.com/kentya6/KYCircularProgress/commit/be2dab67748b6ec5a0bc5f8d716a1d5fc6bf3bc2.

Thanks. :+1:

**Comment by Ahaubster** [comment]
Thanks! It works nicely.
