### ISSUE TITLE
Parameters: startAngle & endAngle don't work 

### ISSUE THREAD

**Issue by olexandr-ls** [kentya6/KYCircularProgress#11]
Thanks for tool.
KYCircularProgress class doesn't handle correctly changing values startAngle & endAngle. 
It happens because of method layoutSubviews in KYCircularShapeView only calls one time (KYCircularShapeView wasn't added as subview). 
I think the KYCircularShapeView should update path every time when we update angle values

**Comment by kentya6** [comment]
Hi, @olexandr-ls .

Sorry for the late reply.
From a conclusion, I'll remove the `startAngle` and `endAngle` property.
I was added their property to use `func addArcWithCenter(_ center: CGPoint, radius radius: CGFloat, startAngle startAngle: CGFloat, endAngle endAngle: CGFloat, clockwise clockwise: Bool)` method. So, `startAngle` and `endAngle` property are only used for this method.
This library can make various style progress bar(in addition to the circular progress), so can't take `start` and `end` criteria from `angle`.
I recommend use `path` property to update your progress path, and use `progress` property to update your progress bar angle.
