### ISSUE TITLE
Circle Offset

### ISSUE THREAD

**Issue by simnik-git** [kentya6/KYCircularProgress#17]
I wanted to implement a gauge with that framework.
I came across an issue where the circle was offset to the right.

<img width="334" alt="gauges" src="https://cloud.githubusercontent.com/assets/10733381/22732392/4d16f9ba-edee-11e6-83f5-0e94c0adac37.png">

I colored the frames of the label (which is centred) and the gauge itself. as you can see the circle is offset. In my implementation I did nothing else then setting the lineWidths and colours

**Comment by kentya6** [comment]
Sorry for the late reply.
Please configure width/height constraint your `KYCircularProgressView`.
You can get correct layout.

**Comment by kentya6** [comment]
If you still have problems, please reopen the issue.
