### ISSUE TITLE
Progress animation should start from current state

### ISSUE THREAD

**Issue by QuentinArnault** [kentya6/KYCircularProgress#22]
If I call `setProgress(progress:duration)` several times, it appears that animations are not updated smoothly. I suspect is due to the fact that when calling `setProgress(progress:duration)` the new animation starts where the previous one ends, even if it is not terminated.

If you confirm my analysis, I can work on a Pull request to correct this.

**Comment by kentya6** [comment]
@QuentinArnault, Thanks for your reporting.
I confirmed it, so I will fix this issue within 24 hours.
If you can create a pull request, I will merge it.

**Comment by kentya6** [comment]
I updated this library to version 1.1.0 and fixed this problem.
Thanks.
