### ISSUE TITLE
CircularProgress.startAngle doesn't take effect

### ISSUE THREAD

**Issue by objcCodingTogether** [kentya6/KYCircularProgress#24]
Hi ,

I just want the animation start from the top of the circle.
So I set the startAngle as **-Double.pi / 2** , but it still start from 0 .
Is there anything I missed?

Here is my code :
    @IBAction func runAction(_ sender: Any) {
        productACircularProgress.colors = [.purple, UIColor(rgba: 0xFFF77 A55), .orange]
        productACircularProgress.startAngle = -Double.pi / 2
        productACircularProgress.set(progress: 0.618, duration: 0.75)
    }

Thanks in advance!

**Comment by kentya6** [comment]
@objcCodingTogether 

I updated to library version 1.2.0.
It added strokeStart / End property, and can set progress offset.
Although it may be enough by CGAffineTransform this time.

Thanks.
