### ISSUE TITLE
update swift4.2

### ISSUE THREAD

**Issue by XiaoChenYung** [kentya6/KYCircularProgress#26]
when update to swift4.2

**Comment by kentya6** [comment]
Hi, @XiaoChenYung 
I updated to Swift 4.2 now.
Thanks, #27

**Comment by kingsofteng** [comment]
@kentya6 
I think we can close this issue.
Please let me know back if you have anything need to be fixed.
Thanks.

**Comment by kentya6** [comment]
ok, thanks!
