### ISSUE TITLE
how can i close KYCircularProgress

### ISSUE THREAD

**Issue by xc19** [kentya6/KYCircularProgress#5]
hello,
i want to close KYCircularProgress.
how can i do.
use removeFromSuperview() can't all remove

**Comment by xc19** [comment]
now must delete KYCircularProgress and textLabel

**Comment by kentya6** [comment]
Hi, xc19.
Do you want to delete `circularProgress1` and `textLabel` variables of my sample project?
If so, please modify from `self.view.addSubview(textLabel)` to `circularProgress1.addSubview(textLabel)` at line 42.
And, write this code: `circularProgress1.removeFromSuperview()`.

**Comment by xc19** [comment]
ok. it's ok.thank you.

**Comment by kentya6** [comment]
OK.
I will fix my sample project as mentioned above.

**Comment by kentya6** [comment]
I fixed this issue. (see https://github.com/kentya6/KYCircularProgress/commit/bf31c710e3e7c6af8241ab426a6c2d6dd8ba8ca2)
Thanks.
