### ISSUE TITLE
Is there any method to give frame and centre point in storyboard?

### ISSUE THREAD

**Issue by willowcheng** [kentya6/KYCircularProgress#8]

**Comment by kentya6** [comment]
Sorry for my slow response.

Currently, there is method to give frame and centre point in storyboard.
But, KYCircularProgress isn't override `awakeFromNib()` function. So, it looks like not appear in storyboard.

I will implement feature to customizable KYCircularProgress via storyboard, within 1 week.

Thank you.

**Comment by kentya6** [comment]
Hi, willowcheng.

I implemented new feature.
Customizable `KYCircularProgress` on Storyboard. (see https://github.com/kentya6/KYCircularProgress/commit/7d9eb503125d6158108bfac01464fc26d2963761)

You can give frame and centre point via Storyboard.

**Comment by willowcheng** [comment]
@kentya6 
Great, excited to hear this news. Thanks for your work!

**Comment by kentya6** [comment]
@willowcheng 
:+1:
