### ISSUE TITLE
Add support to Carthage

### ISSUE THREAD

**Issue by sprint84** [kentya6/KYCircularProgress#9]
I know this might seem overkill for the size of your project, but it would help a lot to keep up with updates.

**Comment by kentya6** [comment]
Hi, @sprint84.

I thought to be trying to support `Carthage` in a few days!
Now, `KYCircularProgress` add support to `Carthage` (see https://github.com/kentya6/KYCircularProgress/commit/8004bc88e069b6ca2d72636bbda7f79940cabdf7)

Thanks. :+1:

**Comment by sprint84** [comment]
You are the best. :)
